apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: node-app
  labels:
    app: node-app
    role: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30080
  selector:
    app: node-app
    role: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: node-app
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: node-app
        role: frontend
    spec:
      containers:
        - name: frontend
          image: sysdiglabs/node-exploit:latest